name: Compilation & tests

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - develop
  pull_request:

jobs:
  job_swap_functional_tests:
    uses: ./.github/workflows/reusable_swap_functional_tests.yml
    with:
      branch_for_exchange: ${{ github.ref }}
      run_for_devices: '["nanos", "nanosp"]'
      test_filter: '"tezos_new"'
